.\" Man page for decompression
.\" David Gold 4/15/18
.TH Huffman Decompression  1 "15 April 2017" "CSCI 241" "Oberlin College"

.SH NAME
.B Huffman decompression
\- A decompression program.
.SH SYNOPSIS
.B sort [Optional Flag]
.SH DESCRIPTION
Program takes user a compressed huffman encoded file and decompresses it.
.SP
 ./encode  my_file.txt
.SH OPTIONS
Can either do 1 file or 2 files, the second one will be interpreted as a file to write to. The first argument is required and is a file to decompress.
.SH AUTHOR
David Gold (Spring 2018)
.SH BUGS
No bugs
